apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    app: {{ include "wordpress.fullname" . }}
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "wordpress.fullname" . }}
      component: wordpress
  template:
    metadata:
      labels:
        app: {{ include "wordpress.fullname" . }}
        component: wordpress
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image }}
          imagePullPolicy: {{ .Values.wordpress.imagePullPolicy }}
          ports:
            - containerPort: 80
          env:
            {{- toYaml .Values.wordpress.env | nindent 12 }}
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: {{ .Values.wordpress.persistence.mountPath }}
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "wordpress.fullname" . }}-wordpress-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-wordpress
  labels:
    app: {{ include "wordpress.fullname" . }}
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "wordpress.fullname" . }}
    component: wordpress
