wordpress:
  image: wordpress:5.6.2-php8.0-apache
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: LoadBalancer
    port: 80
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /var/www/html/wp-content
  env:
    WORDPRESS_DB_HOST: mysql
    WORDPRESS_DB_NAME: wordpress
    WORDPRESS_DB_USER: wordpress
    WORDPRESS_DB_PASSWORD: password
mysql:
  image: mysql:8.0
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /var/lib/mysql
  env:
    MYSQL_ROOT_PASSWORD: root_password
phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
  env:
    PMA_HOST: mysql
    PMA_USER: root
    PMA_PASSWORD: root_password
