apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql.fullname" . }}-mysql
  labels:
    app: {{ include "mysql.fullname" . }}
spec:
  replicas: {{ .Values.mysql.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mysql.fullname" . }}
      component: mysql
  template:
    metadata:
      labels:
        app: {{ include "mysql.fullname" . }}
        component: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          imagePullPolicy: {{ .Values.mysql.imagePullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.fullname" . }}-mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.fullname" . }}-mysql-secret
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.fullname" . }}-mysql-secret
                  key: mysql-password
          ports:
            - containerPort: {{ .Values.mysql.port }}
              protocol: TCP
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: {{ .Values.mysql.persistence.mountPath }}
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ include "mysql.fullname" . }}-mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.fullname" . }}-mysql
  labels:
    app: {{ include "mysql.fullname" . }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: TCP
  selector:
    app: {{ include "mysql.fullname" . }}
    component: mysql
