mysql:
  image: mysql:8.0
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 1Gi
    mountPath: /var/lib/mysql
  env:
    MYSQL_ROOT_PASSWORD: root_password
