apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - name: mysql
      port: {{ .Values.mysql.containerPort }}
      targetPort: mysql
  selector:
    app: mysql