apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: wordpress
spec:
  replicas: {{ .Values.wordpress.replicaCount }}
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: {{ .Values.wordpress.containerName }}
          image: {{ .Values.wordpress.image }}
          ports:
            - containerPort: {{ .Values.wordpress.containerPort }}
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-mysql
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              value: password
            - name: WORDPRESS_DB_NAME
              value: {{ .Values.wordpress.dbName }}
